-- Starmourn Voidgate Navigator

-- Credits:
-- - Original code from Maruna's post on the Starmourn forums.
--   - https://forums.starmourn.com/discussion/760/voidgates-for-lazy-people

smvgn.voidgates = {
	a = "Aleph",
	b = "Song",
	c = "Celestine",
	d = "Scatterhome",
	e = "Hreysil",
	f = "Ironcorsairs",
	g = "Arcturus",
	h = "Nabian",
	i = "Narchspace",
	j = "Grensuhlian",
	k = "Vonikinkrel",
	l = "Diamondbelt",
	m = "Syndicate",
	n = "Fatar",
	o = "Selassian",
	p = "Zinari",
	q = "Laskarid",
	r = "Neutralspace",
	s = "Ibyssian",
}

smvgn.voidgate_destinations = {	
	Aleph = {
		Song = {"b"},
		Celestine = {"c"},
		Scatterhome = {"d"},
		Hreysil = {"e"},
		Ironcorsairs = {"e", "f"},
		Arcturus = {"e", "f", "g"},
		Nabian = {"h"},
		Narchspace = {"c", "i"},
		Grensuhlian = {"d", "j"},
		Vonikinkrel = {"k"},
		Diamondbelt = {"b", "l"},
		Syndicate = {"b", "l", "m"},
		Fatar = {"h", "o", "n"},
		Selassian = {"h", "o"},
		Zinari = {"h", "o", "p"},
		Laskarid = {"h", "o", "p", "q"},
		Neutralspace = {"h", "o", "p", "q", "r"},
		Ibyssian = {"h", "o", "p", "q", "r", "s"},	
	},

	Song = {
		Aleph = {"a"},
		Celestine = {"a", "c"},
		Scatterhome = {"a", "d"},
		Hreysil = {"a", "e"},
		Ironcorsairs = {"a", "e", "f"},
		Arcturus = {"a", "e", "f", "g"},
		Nabian = {"a", "h"},
		Narchspace = {"a", "c", "i"},
		Grensuhlian = {"a", "d", "j"},
		Vonikinkrel = {"a", "k"},
		Diamondbelt = {"l"},
		Syndicate = {"l", "m"},
		Fatar = {"l", "m", "n"},
		Selassian = {"a", "h", "o"},
		Zinari = {"a","h", "o", "p"},
		Laskarid = {"a", "h", "o", "p", "q"},
		Neutralspace = {"a", "h", "o", "p", "q", "r"},
		Ibyssian = {"a", "h", "o", "p", "q", "r", "s"},	
	},
	
	Celestine = {
		Song = {"a", "b"},
		Aleph = {"a"},
		Scatterhome = {"a", "d"},
		Hreysil = {"a", "e"},
		Ironcorsairs = {"a", "e", "f"},
		Arcturus = {"a", "e", "f", "g"},
		Nabian = {"a", "h"},
		Narchspace = {"i"},
		Grensuhlian = {"a", "d", "j"},
		Vonikinkrel = {"a", "k"},
		Diamondbelt = {"a", "b", "l"},
		Syndicate = {"a", "b", "l", "m"},
		Fatar = {"a", "b", "l", "m", "n"},
		Selassian = {"a", "h", "o"},
		Zinari = {"a","h", "o", "p"},
		Laskarid = {"a", "h", "o", "p", "q"},
		Neutralspace = {"a", "h", "o", "p", "q", "r"},
		Ibyssian = {"a", "h", "o", "p", "q", "r", "s"},	
	},

	Scatterhome = {
		Song = {"a", "b"},
		Celestine = {"a", "c"},
		Aleph = {"a"},
		Hreysil = {"a", "e"},
		Ironcorsairs = {"a", "e", "f"},
		Arcturus = {"a", "e", "f", "g"},
		Nabian = {"a", "h"},
		Narchspace = {"a", "c", "i"},
		Grensuhlian = {"j"},
		Vonikinkrel = {"k"},
		Diamondbelt = {"a", "b", "l"},
		Syndicate = {"a", "b", "l", "m"},
		Fatar = {"a", "b", "l", "m", "n"},
		Selassian = {"a", "h", "o"},
		Zinari = {"a","h", "o", "p"},
		Laskarid = {"a", "h", "o", "p", "q"},
		Neutralspace = {"a", "h", "o", "p", "q", "r"},
		Ibyssian = {"a", "h", "o", "p", "q", "r", "s"},	
	},
	
	Hreysil = {
		Song = {"a", "b"},
		Celestine = {"a", "c"},
		Scatterhome = {"a", "d"},
		Aleph = {"a"},
		Ironcorsairs = {"f"},
		Arcturus = {"f", "g"},
		Nabian = {"a", "h"},
		Narchspace = {"a", "c", "i"},
		Grensuhlian = {"j"},
		Vonikinkrel = {"a", "k"},
		Diamondbelt = {"a", "b", "l"},
		Syndicate = {"a", "b", "l", "m"},
		Fatar = {"a", "h", "o", "n"},
		Selassian = {"a", "h", "o"},
		Zinari = {"a", "h", "o", "p"},
		Laskarid = {"a", "h", "o", "p", "q"},
		Neutralspace = {"a", "h", "o", "p", "q", "r"},
		Ibyssian = {"a", "h", "o", "p", "q", "r", "s"},
	},
	
	Ironcorsairs = {
		Song = {"e", "a", "b"},
		Celestine = {"e", "a", "c"},
		Scatterhome = {"e", "a", "d"},
		Hreysil = {"e"},
		Aleph = {"e", "a"},
		Arcturus = {"g"},
		Nabian = {"e", "a", "h"},
		Narchspace = {"e", "a", "c", "i"},
		Grensuhlian = {"e", "j"},
		Vonikinkrel = {"e", "a", "k"},
		Diamondbelt = {"e", "a", "b", "l"},
		Syndicate = {"e", "a", "b", "l", "m"},
		Fatar = {"e", "a", "h", "o", "n"},
		Selassian = {"e", "a", "h", "o"},
		Zinari = {"e", "a", "h", "o", "p"},
		Laskarid = {"e", "a", "h", "o", "p", "q"},
		Neutralspace = {"e", "a", "h", "o", "p", "q", "r"},
		Ibyssian = {"e", "a", "h", "o", "p", "q", "r", "s"},
	},

	Arcturus = {
		Song = {"f", "e", "a", "b"},
		Celestine = {"f", "e", "a", "c"},
		Scatterhome = {"f", "e", "a", "d"},
		Hreysil = {"f", "e"},
		Aleph = {"f", "e", "a"},
		Ironcorsairs = {"f"},
		Nabian = {"f", "e", "a", "h"},
		Narchspace = {"f", "e", "a", "c", "i"},
		Grensuhlian = {"f", "e", "j"},
		Vonikinkrel = {"f", "e", "a", "k"},
		Diamondbelt = {"f", "e", "a", "b", "l"},
		Syndicate = {"f", "e", "a", "b", "l", "m"},
		Fatar = {"f", "e", "a", "h", "o", "n"},
		Selassian = {"f", "e", "a", "h", "o"},
		Zinari = {"f", "e", "a", "h", "o", "p"},
		Laskarid = {"f", "e", "a", "h", "o", "p", "q"},
		Neutralspace = {"f", "e", "a", "h", "o", "p", "q", "r"},
		Ibyssian = {"f", "e", "a", "h", "o", "p", "q", "r", "s"},
	},
	
	Nabian = {
		Song = {"a", "b"},
		Celestine = {"a", "c"},
		Scatterhome = {"a", "d"},
		Hreysil = {"a", "e"},
		Ironcorsairs = {"a", "e", "f"},
		Arcturus = {"a", "e", "f", "g"},
		Aleph = {"a"},
		Narchspace = {"a", "c", "i"},
		Grensuhlian = {"a", "e", "j"},
		Vonikinkrel = {"a", "k"},
		Diamondbelt = {"a", "b", "l"},
		Syndicate = {"o", "n", "m"},
		Fatar = {"o", "n"},
		Selassian = {"o"},
		Zinari = {"o", "p"},
		Laskarid = {"o", "p", "q"},
		Neutralspace = {"o", "p", "q", "r"},
		Ibyssian = {"o", "p", "q", "r", "s"},
	},

	Narchspace = {
		Song = {"c", "a", "b"},
		Celestine = {"c"},
		Scatterhome = {"c", "a", "d"},
		Hreysil = {"c", "a", "e"},
		Ironcorsairs = {"c", "a", "e", "f"},
		Arcturus = {"c", "a", "e", "f", "g"},
		Nabian = {"c", "a", "h"},
		Aleph = {"c", "a" },
		Grensuhlian = {"c", "a", "d", "j"},
		Vonikinkrel = {"c", "a", "k"},
		Diamondbelt = {"c", "a", "b", "l"},
		Syndicate = {"c", "a", "b", "l", "m"},
		Fatar = {"c", "a", "h", "o", "n"},
		Selassian = {"c", "a", "h","o"},
		Zinari = {"c", "a", "h","o", "p"},
		Laskarid = {"c", "a", "h","o", "p", "q"},
		Neutralspace = {"c", "a", "h","o", "p", "q", "r"},
		Ibyssian = {"c", "a", "h", "o", "p", "q", "r", "s"},
	},
	
	Grensuhlian = {
		Song = {"e", "a", "b"},
		Celestine = {"e", "a", "c"},
		Scatterhome = {"d"},
		Hreysil = {"e"},
		Ironcorsairs = {"e", "f"},
		Arcturus = {"e", "f", "g"},
		Nabian = {"e", "a", "h"},
		Narchspace = {"e", "a", "c", "i"},
		Aleph = {"e", "a"},
		Vonikinkrel = {"d", "k"},
		Diamondbelt = {"e", "a", "b", "l"},
		Syndicate = {"e", "a", "b", "l", "m"},
		Fatar = {"e", "a", "h", "o", "n"},
		Selassian = {"e", "a", "h","o"},
		Zinari = {"e", "a", "h","o", "p"},
		Laskarid = {"e", "a", "h","o", "p", "q"},
		Neutralspace = {"e", "a", "h","o", "p", "q", "r"},
		Ibyssian = {"e", "a", "h", "o", "p", "q", "r", "s"},
	},

	Vonikinkrel = {
		Song = {"a", "b"},
		Celestine = {"a", "c"},
		Scatterhome = {"d"},
		Hreysil = {"a", "e"},
		Ironcorsairs = {"a", "e", "f"},
		Arcturus = {"a", "e", "f", "g"},
		Nabian = {"a", "h"},
		Narchspace = {"a", "c", "i"},
		Grensuhlian = {"d", "j"},
		Aleph = {"a"},
		Diamondbelt = {"a", "b", "l"},
		Syndicate = {"a", "b", "l", "m"},
		Fatar = { "a", "h", "o", "n"},
		Selassian =  {"a", "h","o"},
		Zinari = { "a", "h","o", "p"},
		Laskarid = { "a", "h","o", "p", "q"},
		Neutralspace = { "a", "h","o", "p", "q", "r"},
		Ibyssian = {"a", "h", "o", "p", "q", "r", "s"},
	},
	
	Diamondbelt = {
		Song = {"b"},
		Celestine = {"b", "a", "c"},
		Scatterhome = {"b", "a", "d"},
		Hreysil = {"b", "a", "e"},
		Ironcorsairs = {"b", "a", "e", "f"},
		Arcturus = {"b", "a", "e", "f", "g"},
		Nabian = {"b", "a", "h"},
		Narchspace = {"b", "a", "c", "i"},
		Grensuhlian = {"b", "a", "e", "j"},
		Vonikinkrel = {"b", "a", "k"},
		Aleph = {"b", "a"},
		Syndicate = {"m"},
		Fatar = {"m", "n"},
		Selassian = {"m", "n", "o"},
		Zinari = {"m", "n", "o", "p"},
		Laskarid = {"m", "n", "o", "p", "q"},
		Neutralspace = {"m", "n", "o", "p", "q", "r"},
		Ibyssian = {"m", "n", "o", "p", "q", "r", "s"},
	},

	Syndicate = {
		Song = {"l", "b"},
		Celestine = {"l", "b", "a", "c"},
		Scatterhome = {"l", "b", "a", "d"},
		Hreysil = {"l", "b", "a", "e"},
		Ironcorsairs = {"l", "b", "a", "e", "f"},
		Arcturus = {"l", "b", "a", "e", "f", "g"},
		Nabian = {"n", "o", "h"},
		Narchspace = {"l", "b", "a", "c", "i"},
		Grensuhlian = {"l", "b", "a", "e", "j"},
		Vonikinkrel = {"l", "b", "a", "k"},
		Diamondbelt = {"l"},
		Aleph = {"l", "b", "a"},
		Fatar = {"n"},
		Selassian = {"n", "o"},
		Zinari = {"n", "o", "p"},
		Laskarid = {"n", "o", "p", "q"},
		Neutralspace = {"n", "o", "p", "q", "r"},
		Ibyssian = {"n", "o", "p", "q", "r", "s"},
	},

	Fatar = {
		Song = {"m", "l", "b"},
		Celestine = {"o", "h", "a", "c",},
		Scatterhome = {"o", "h", "a", "d"},
		Hreysil = {"o", "h", "a", "e"},
		Ironcorsairs = {"o", "h", "a", "e", "f"},
		Arcturus = {"o", "h", "a", "e", "f", "g"},
		Nabian = {"o", "h"},
		Narchspace = {"o", "h", "a", "c", "i"},
		Grensuhlian = {"o", "h", "a", "e", "j"},
		Vonikinkrel = {"o", "h", "a", "k"},
		Diamondbelt = {"m", "l"},
		Syndicate = {"m"},
		Aleph = {"o", "h", "a"},
		Selassian = {"o"},
		Zinari = {"o", "p"},
		Laskarid = {"o", "p", "q"},
		Neutralspace = {"o", "p", "q", "r"},
		Ibyssian = {"o", "p", "q", "r", "s"},
	},

	Selassian = {
		Song = {"h", "a", "b"},
		Celestine = {"h", "a", "c"},
		Scatterhome = {"h", "a", "d"},
		Hreysil = {"h", "a", "e"},
		Ironcorsairs = {"h", "a", "e", "f"},
		Arcturus = {"h", "a", "e", "f", "g"},
		Nabian = {"h"},
		Narchspace = {"h", "a", "c", "i"},
		Grensuhlian = {"h", "a", "e", "j"},
		Vonikinkrel = {"h", "a", "k"},
		Diamondbelt = {"n", "m", "l"},
		Syndicate = {"n", "m"},
		Fatar = {"n"},
		Aleph = {"h", "a"},
		Zinari = {"p"},
		Laskarid = {"p", "q"},
		Neutralspace = {"p", "q", "r"},
		Ibyssian = {"p", "q", "r", "s"},
	},

	Zinari = {
		Song = {"o", "h", "a", "b"},
		Celestine = {"o", "h", "a", "c"},
		Scatterhome = {"o", "h", "a", "d"},
		Hreysil = {"o", "h", "a", "e"},
		Ironcorsairs = {"o", "h", "a", "e", "f"},
		Arcturus = {"o", "h", "a", "e", "f", "g"},
		Nabian = {"o", "h"},
		Narchspace = {"o", "h", "a", "c", "i"},
		Grensuhlian = {"o", "h", "a", "e", "j"},
		Vonikinkrel = {"o", "h", "a", "k"},
		Diamondbelt = {"o", "n", "m", "l"},
		Syndicate = {"o", "n", "m"},
		Fatar = {"o", "n"},
		Selassian = {"o"},
		Aleph = {"o", "h", "a"},
		Laskarid = {"q"},
		Neutralspace = {"q", "r"},
		Ibyssian = {"q", "r", "s"},
	},

	Laskarid = {
		Song = {"p", "o", "h", "a", "b"},
		Celestine = {"p", "o", "h", "a", "c"},
		Scatterhome = {"p", "o", "h", "a", "d"},
		Hreysil = {"p", "o", "h", "a", "e"},
		Ironcorsairs = {"p", "o", "h", "a", "e", "f"},
		Arcturus = {"p", "o", "h", "a", "e", "f", "g"},
		Nabian = {"p", "o", "h"},
		Narchspace = {"p", "o", "h", "a", "c", "i"},
		Grensuhlian = {"p", "o", "h", "a", "e", "j"},
		Vonikinkrel = {"p", "o", "h", "a", "k"},
		Diamondbelt = {"p", "o", "n", "m", "l"},
		Syndicate = {"p", "o", "n", "m"},
		Fatar = {"p", "o", "n"},
		Selassian = {"p", "o"},
		Zinari = {"p"},
		Aleph = {"p", "o", "h", "a"},
		Neutralspace = {"r"},
		Ibyssian = {"r", "s"},
	},

	Neutralspace = {
		Song = {"q", "p", "o", "h", "a", "b"},
		Celestine = {"q", "p", "o", "h", "a", "c"},
		Scatterhome = {"q", "p", "o", "h", "a", "d"},
		Hreysil = {"q", "p", "o", "h", "a", "e"},
		Ironcorsairs = {"q", "p", "o", "h", "a", "e", "f"},
		Arcturus = {"q", "p", "o", "h", "a", "e", "f", "g"},
		Nabian = {"q", "p", "o", "h"},
		Narchspace = {"q", "p", "o", "h", "a", "c", "i"},
		Grensuhlian = {"q", "p", "o", "h", "a", "e", "j"},
		Vonikinkrel = {"q", "p", "o", "h", "a", "k"},
		Diamondbelt = {"q", "p", "o", "n", "m", "l"},
		Syndicate = {"q", "p", "o", "n", "m"},
		Fatar = {"q", "p", "o", "n"},
		Selassian = {"q", "p", "o"},
		Zinari = {"q", "p"},
		Laskarid = {"q"},
		Aleph = {"q", "p", "o", "h", "a"},
		Ibyssian = {"s"},
	},
	
		Ibyssian = {
		Song = {"r", "q", "p", "o", "h", "a", "b"},
		Celestine = {"r", "q", "p", "o", "h", "a", "c"},
		Scatterhome = {"r", "q", "p", "o", "h", "a", "d"},
		Hreysil = {"r", "q", "p", "o", "h", "a", "e"},
		Ironcorsairs = {"r", "q", "p", "o", "h", "a", "e", "f"},
		Arcturus = {"r", "q", "p", "o", "h", "a", "e", "f", "g"},
		Nabian = {"r", "q", "p", "o", "h"},
		Narchspace = {"r", "q", "p", "o", "h", "a", "c", "i"},
		Grensuhlian = {"r", "q", "p", "o", "h", "a", "e", "j"},
		Vonikinkrel = {"r", "q", "p", "o", "h", "a", "k"},
		Diamondbelt = {"r", "q", "p", "o", "n", "m", "l"},
		Syndicate = {"r", "q", "p", "o", "n", "m"},
		Fatar = {"r", "q", "p", "o", "n"},
		Selassian = {"r", "q", "p", "o"},
		Zinari = {"r", "q", "p"},
		Laskarid = {"r", "q"},
		Neutralspace = {"r"},
		Aleph = {"r", "q", "p", "o", "h", "a"},
	}
}
